version: "2"
services:
  app:
    container_name: "bayview-development"
    build:
      context: .
      target: build
    command: npm run test
    networks:
      - app_network
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
    volumes:
      - app:/app
      - node_modules:/app/node_modules
      - next:/app/.next

networks:
  app_network:
    driver: bridge

volumes:
  app: {}
  next: {}
  node_modules: {}
