version: '2'
services:
    app:
        container_name: bayview-development
        build: 
          context: .
          target: dev
        command: 
            ash -c "npm run build && npm run test"
        ports:
            - 51204:51204
        volumes:
            - .:/app
            - /app/node_modules
            - /app/.next
            - /app/__vitest__/

volumes:
    bayview-nodemodules: {}
