version: '1'
services:
    app:
        container_name: bayview-development
        build: 
          context: .
          target: dev
        command: 
            npm run build |
            npm run test
        volumes:
            - .:/app
            - /app/node_modules
            - /app/.next

volumes:
    bayview-nodemodules: {}
